For:《Python语言与应用》<br>
By：上海大杨晓明<br>
Created date: 2020.03.27

# Chapter_06_02 numpy矩阵



## 矩阵和数组的关系

- 形式上很像，矩阵是数学上的概念，而数组是一种数据存储方式。
- 矩阵只能包含数字，而数组可以包含任意类型数据；
- 矩阵是二维的，数组可以是任意维的；
- 乘法、幂运算等很多运算的规则与数组也不一样。

## 6.2.1  生成矩阵


### 1 matrix()函数
可以把列表、元祖、range()对象、等Python可迭代对象转换为矩阵。

In [1]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6]])
x

matrix([[1, 2, 3],
        [4, 5, 6]])

In [3]:
y = np.matrix([1,2,3,4,5,6])
y

matrix([[1, 2, 3, 4, 5, 6]])

In [4]:
# x[1,1]返回行下标和列下标都为1的元素
# 注意，对于矩阵x来说，x[1,1]和x[1][1]的含义不一样
print(x, y, x[1,1], sep='\n\n')

[[1 2 3]
 [4 5 6]]

[[1 2 3 4 5 6]]

5


## 6.2.2  矩阵转置

### 1 T函数

In [ ]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6]])
y = np.matrix([1,2,3,4,5,6])
print(x.T, y.T, sep='\n\n')


## 6.2.3  查看矩阵特征

### 1 mean()

In [5]:
import numpy as np
x = np.matrix([[1,2,3], [4,5,6]])
x

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
x.mean()          # 所有元素平均值

3.5

In [8]:
x.mean(axis=0)     # 纵向平均值

matrix([[2.5, 3.5, 4.5]])

In [9]:
x.mean(axis=1)    # 

matrix([[2.],
        [5.]])

In [10]:
x.mean(axis=0).shape

(1, 3)

In [11]:
x.mean(axis=1)      # 横向平均值

matrix([[2.],
        [5.]])

### 2 sum

In [12]:
x.sum()              # 所有元素之和

21

SyntaxError: invalid character in identifier (<ipython-input-13-34086cd28472>, line 1)

### 3 max, argmax, diagonal, nonzero, 

In [17]:
x.max(axis=0)       # 横向最大值

matrix([[4, 5, 6]])

In [18]:
x.argmax(axis=0)     # 横向最大值的下标

matrix([[1, 1, 1]], dtype=int64)

In [19]:
x.diagonal()       # 对角线元素

matrix([[1, 5]])

In [20]:
x.nonzero()             # 非0元素下标，分别返回行下标和列下标

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

## 6.2.4  矩阵乘法

In [22]:
import numpy as np

x = np.matrix([[1,2,3], [4,5,6]])
x

matrix([[1, 2, 3],
        [4, 5, 6]])

In [21]:
y = np.matrix([[1,2], [3,4], [5,6]])
y

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
print(x*y)

[[22 28]
 [49 64]]


## 6.2.5  计算相关系数矩阵

- 相关系数矩阵是一个对称矩阵，其中对角线上的元素都是1，表示自相关系数。
- 非对角线元素表示互相关系数，每个元素的绝对值都小于等于1，反应变量变化趋势的相似程度。<br>
- 例如，如果的相关系数矩阵中非对角线元素大于0，表示两个信号正相关，其中一个信号变大时另一个信号也变大，变化方向一致，或者说一个信号的变化对另一个信号的影响是“正面”的或者积极的。
- 相关系数的绝对值越大，表示两个信号互相影响的程度越大。


In [24]:
import numpy as np
np.corrcoef([1,2,3,4], [4,3,2,1])  #负相关，变化方向相反

#     x   y
# x  1  -1
# y -1   1

array([[ 1., -1.],
       [-1.,  1.]])

In [25]:
np.corrcoef([1,2,3,4], [8,3,2,1])  #负相关，变化方向相反

array([[ 1.        , -0.91350028],
       [-0.91350028,  1.        ]])

In [26]:
np.corrcoef([1,2,3,4], [1,2,3,4])  #正相关，变化方向一致

array([[1., 1.],
       [1., 1.]])

In [27]:
np.corrcoef([1,2,3,4], [1,2,3,40]) #正相关，变化趋势接近

array([[1.       , 0.8010362],
       [0.8010362, 1.       ]])

## 6.2.6 NumPy的统计函数

计算方差、协方差、标准差
np.var(),np.cov()，np.std()

#### NumPy的统计函数（1）

|函数|说明|
|--|--|
|sum(a,axis=None)|根据给定轴axis计算数组a相关元素之和，axis整数或数组|
|mean(a,axis=None)|根据给定轴axis计算数组a相关元素的期望，axis整数或数组|
|average(a,axis=None,weights=None)|根据给定轴axis计算数组a相关元素的加权平均值|
|std(a,axis=None)|根据给定轴axis计算数组a相关元素的标准差|
|var(a,axis=None)|根据给定轴axis计算数组a相关元素之方差|

In [28]:
## 计算方差、协方差、标准差

import numpy as np

print(np.cov([1,1,1,1,1]))         # 方差
print(np.std([1,1,1,1,1]))         # 标准差

0.0
0.0


In [29]:
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X = np.vstack((x,y))               # 垂直堆叠矩阵
X

array([[-2.1 , -1.  ,  4.3 ],
       [ 3.  ,  1.1 ,  0.12]])

In [35]:
np.cov(X)                   # 协方差

array([[11.71      , -4.286     ],
       [-4.286     ,  2.14413333]])

In [34]:
np.cov(x, y)

array([[11.71      , -4.286     ],
       [-4.286     ,  2.14413333]])

In [37]:
print(np.std(X))                   # 标准差

2.2071223094538484


In [38]:
print(np.std(X, axis=1))

[2.79404128 1.19558447]


In [39]:
print(np.cov(x))                   # 方差

11.709999999999999


#### NumPy的统计函数（2）

|函数|说明|
|--|--|
|min(a) max(a)|计算数组a中元素的最小值、最大值|
|argmin(a) argmax(a)|计算数组a中元素的最小值、最大值的降一维后下标|
|unravel_index(index,shape)|根据shape将一维下标index转换成多维下标|
|ptp(a)|计算数组a中元素的最大值与最小值的差|
|median(a)|计算数组a中元素的中位数（中值）|

# 6.3  计算特征值与特征向量

# 6.4  计算逆矩阵

# 6.5  求解线性方程组

# 6.6  计算向量和矩阵的范数

# 6.7  奇异值分解

# 6.8  函数向量化