> For:《Python语言与应用》<br>
> By：上海大杨晓明<br>
> Created date: 2020.03.27
---

# Chapter_06_01 numpy数组及其运算(1)

## 6.0 基础知识

### 6.0.1NumPy是一个开源的Python科学计算基础库，包含：
- 一个强大的N维数组对象 ndarray
- 广播功能函数
- 整合C/C++/Fortran代码的工具
- 线性代数、傅里叶变换、随机数生成等功能

NumPy是SciPy、Pandas等数据处理或科学计算库的基础

### 6.0.2 Numpy的主要对象是**同质的多维数组**。

  其中的元素通常都是**数字**，并且是同样的类型，由一个正整数元组进行索引。每个元素在内存中占有同样大小的空间。

- 在Numpy中，维度被称为‘轴’。

> 例如对于[1, 2, 1]我们说它有一个轴，并且长度为3。而[[ 1., 0., 0.], [ 0., 1., 2.]]则有两个轴，第一个轴的长度为2，第二个轴的长度为3。

- Numpy数组类的名字叫做`ndarray`.

- `np.array`的代码定义如下：

     `numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)`

各参数的含义：

`object`：用于生成数组的数据对象<br>
`dtype`：指定类型，可选。<br>
`copy`：可选，默认为`True`，对象被复制。<br>
`order`：C语言风格（按行）、FORTRAN风格（按列）或A（任意，默认）。<br>
`subok`：默认情况下，返回的数组被强制为基类数组。 如果为`Tru`e，则返回子类。<br>
`ndmin`：指定返回数组的最小维数。<br>

### 6.0.3 `ndarray`具有以下重要属性：

`ndarray.ndim`：数组的轴数量<br>
`ndarray.shape`：数组的形状。这是一个整数元组。比如对于n行m列的矩阵，其shape形状就是(n,m)。而shape元组的长度则恰恰是上面的ndim值，也就是轴数。<br>
`ndarray.size`：数组中所有元素的个数。这恰好等于shape中元素的乘积。<br>
`ndarray.dtype`：数组中元素的数据类型。除了标准的Python类型，Numpy还提供一些自有的类型。<br>
`ndarray.itemsize`：元素的字节大小。比如float64类型的itemsize为8（=64/8），而complex32的itemsize为4（=32/8）。<br>
`ndarray.data`：包含数组实际元素的缓冲区。通常我们不需要使用这个属性，因为我们将使用索引工具访问数组中的元素。<br>
`ndarray.flags`: 数组对象的一些状态指示或标签

### 6.0.4 在实际使用中，我们通常使用`import numpy as np`来导入numpy并简写为np，这是国际惯例，请保持阵型。

In [1]:
import numpy as np  #导入numpy
a = np.arange(15).reshape(3, 5) #创建一个数组并调整为3行5列
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
# from numpy import *

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim()

TypeError: 'int' object is not callable

In [4]:
a.dtype.name  # 根据版本和环境不同，可能不同，比如int64

'int32'

In [5]:
a.itemsize

4

In [6]:
a.size

15

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])  # 又一种生成数组的方法
b

array([6, 7, 8])

In [10]:
b.shape


(3,)

### 6.0.5 Numpy还有一些预先定义的特殊值：

 比如：`np.nan、np.pi、np.e`

`np.nan`： 缺失值，或者理解为'不是一个数'

`np.pi`:圆周率 3.1415926...

`np.e`:自然数e 2.718281828459045...

In [12]:
import numpy as np 
a = np.array([np.nan,1,2,np.nan,3,4,5]) 
a

array([nan,  1.,  2., nan,  3.,  4.,  5.])

In [13]:
a[~np.isnan(a)]   # ~


array([1., 2., 3., 4., 5.])

In [14]:
b = np.array([1,  2+6j,  5,  3.5+5j])  
b[np.iscomplex(b)]

array([2. +6.j, 3.5+5.j])

### 6.1.1 创建数组

创建Numpy数组一般有三种方法：

（1）通过传入可待跌对象创建，我将之称为基本方法<br>
（2）使用Numpy内部功能函数，内部方法<br>
（3）使用特殊的库函数，特殊方法

#### 1 使用`array`方法
   供标准的Python**列表**或者**元组**作为参数。此时，数组的类型将根据序列中元素的类型推导出来。

In [15]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [18]:
a.dtype

dtype('int32')

In [17]:
b = np.array((1.2, 3.5, 5.1))
b

array([1.2, 3.5, 5.1])

常见的错误是直接将多个数值作为参数传递，正确的做法是将他们以**列表或元组**的方式传递，如下：

In [21]:
a = np.array((1,2,3,4) )   # 错误
a

array([1, 2, 3, 4])

In [ ]:
a = np.array([1,2,3,4])  # 正确
a

array函数会自动将二维或三维序列转换为对应的二维或三维数组。

In [22]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

在创建的时候，可以显式地指定数据的类型：

In [23]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

那么我们只能玩数字么？不是的，字符串也可以，只是我们不常用而已：

In [24]:
s = 'hellow world'
c = np.array(s)
c

array('hellow world', dtype='<U12')

甚至还可以接受**range()**返回的可迭代对象作为参数：

In [27]:
np.array(range(10, 20, 2))

array([10, 12, 14, 16, 18])

In [26]:
list(range(10, 20, 2))

[10, 12, 14, 16, 18]

#### 2 通用方法：np.ones()、np.zeros()、np.eye()、np.empty()
函数`zero`创建一个都是0的数组，函数one创建一个都是1的数组，函数`empty`创建一个初始内容是0或者垃圾值的数组，这取决于内存当时的状态。默认情况下，创建的数组的数据类型为float64。

In [28]:
np.zeros((5,), dtype = np.float)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones( (2,3,4), dtype=np.int16 )                # 同样可以指定类型

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [31]:
np.empty( (2,3) )   # 根据当前内存状态的不同，可能会返回未初始化的垃圾数值，不安全。

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [32]:
np.full((3,4), 2.2) # 创建一个全部由2.22组成的数组

array([[2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2]])

#### 3 特殊方法

##### （1）arange()
Numpy还提供了一个返回array序列的函数，而不是返回一个Python的列表，这就是常用的arange函数：

In [33]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [34]:
np.arange( 0, 2, 0.3 )                 # 可以接受浮点类型的参数，比如这里的步长

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

- 其原型为：

numpy.arange(start, stop, step, dtype)

    start：范围的起始值，默认为0
    stop： 范围的终止值（不包含）
    step： 两个值的间隔，默认为1
    dtype： 返回ndarray的数据类型，如果没有提供，则会使用输入数据的类型。

##### (2) linspace()

`linspace`函数，它的第三个参数指定在区间内均匀生成几个数，至于步长，系统会自动计算。

In [35]:
from numpy import pi  # 导入圆周率
np.linspace( 0, 2, 9 )                 # 从0到2之间的9个数

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [36]:
x = np.linspace( 0, 2*pi, 100 )        # 从0到2Π之间，生成100个数
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

- 其原型为：

`numpy.linspace(start, stop, num, endpoint, retstep, dtype)`

`start`： 序列的起始值<br>
`stop`： 序列的终止值，如果`endpoint`为`True`，则终止值包含于序列中<br>
`num`： 要生成的等间隔样例数量，默认为`50`<br>
`endpoint`： 序列中是否包含stop值，默认为`Ture`<br>
`retstep`： 如果为`True`，返回样例以及连续数字之间的步长<br>
`dtype`： 输出`ndarray`的数据类型<br>

##### (3) 更多类似的函数有：

`array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile`

In [37]:
np.logspace(0, 100, 10)          # 相当于10**np.linspace(0,100,10)

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [ ]:
np.logspace(1,6,5, base=2)       # 相当于2 ** np.linspace(1,6,5)

In [41]:
np.zeros(3)                      # 全0一维数组

array([0., 0., 0.])

In [40]:
np.ones(3)                       # 全1一维数组

array([1., 1., 1.])

In [39]:
np.zeros((3,3))                  # 全0二维数组，3行3列

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.identity(3)                     # 单位矩阵，3行3列

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.random.randint(0, 50, 5)      # 随机数组，5个0到50之间的数字

array([48, 24, 41, 34, 18])

In [64]:
np.random.randint(0, 50, (3,5))  # 3行5列，共15个随机数，都介于[0,50)

array([[ 5, 37, 45, 44, 36],
       [49,  6, 49, 20,  4],
       [ 5, 20, 44, 33, 22]])

In [ ]:
np.random.rand(10)               # 10个介于[0,1)的随机数

In [67]:
np.random.standard_normal(5)     # 从标准正态分布中随机采样5个数字

array([-1.04281101, -1.47809369, -0.95554033, -0.91126987,  0.05362179])

In [68]:
x = np.random.standard_normal(size=(3, 4, 2))
x

array([[[-0.49556201,  0.72253654],
        [ 0.93004285,  0.43248735],
        [-1.2498637 ,  0.41603869],
        [ 0.79871704,  0.27869685]],

       [[ 1.16892215, -0.87627052],
        [-0.1288569 , -0.8376619 ],
        [-0.54616519,  0.99332925],
        [-0.62385535, -1.12536919]],

       [[ 1.65261525,  0.16940175],
        [-0.96708337,  0.71569427],
        [ 0.22475224,  1.72108558],
        [-1.02616823,  1.76735533]]])

In [69]:
np.diag([1,2,3,4])                 # 对角矩阵

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [70]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4 读取外部数据

numpy也支持从外部读取数据来创建数组，例如从硬盘中读取csv、txt等文件来创建数组。np.genfromtxt()是numpy中读取文件的一个方法，例如在当前目录下有一个data.csv文件，文件内容为：

```
    id,height,length
    1,100,101
    2,200,230
    3,300,350
```

通过numpy读取：

In [ ]:
np.genfromtxt('data.csv',delimiter=',',skip_header=1)

`array([[ 1., 100., 101.],[ 2., 200., 230.],[ 3., 300., 350.]])`

读取外部数据的方法不止np.genfromtxt()，还有np.load()等，但numpy读取外部数据的应用情况其实并不多，这里不再细说。

## 6.1.2  测试两个数组的对应元素是否足够接近

`isclose()`,`allclose()`函数来测试两个数组中对应位置上的元素在允许的范围内是否相等。并可以接收绝对误差参数和相对误差参数。
- `isclose()`用来测试每一对元素是否相等并返回若干`True/False`的列表
- `allclose()`用来测试所有对应位置上的元素是否相等，并返回单个`True`或`False`。

In [71]:
import numpy as np
x = np.array([1, 2, 3, 4.001, 5])
y = np.array([1, 1.999, 3, 4.01, 5.1])

In [73]:
print(np.isclose(x, y))

[ True False  True False False]


In [74]:
print(np.allclose(x, y, rtol=0.2))       # 设置相对误差参数
print(np.allclose(x, y, atol=0.2))       # 设置绝对误差参数

True
True


In [75]:
print(np.isclose(x, y))
print(np.isclose(x, y, atol=0.2))

[ True False  True False False]
[ True  True  True  True  True]


## 6.1.3  修改数组中的元素值

下面是几个常见的数组操作：

`append`:将值添加到数组末尾<br>
`insert`: 沿指定轴将值插入到指定下标之前<br>
`delete`: 返回删掉某个轴的子数组的新数组<br>
`unique`: 寻找数组内的唯一元素<br>


### 1 append()

In [76]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) 
np.append(a, [7,8,9])  # 附加后，变成了一维的

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a  #原来的数组没有改变

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.append([10,11,12]) # ndarray没有这个方法

In [78]:
np.append(a, [[7,8,9]],axis = 0)  # 注意参数格式

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.append(a, [[7],[8],[9]],axis = 1)  # 注意参数格式

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

### 2 insert()

In [80]:
a = np.array([[1,2],[3,4],[5,6]])
np.insert(a,3,[11,12])     # 在3号位置前插入，变成一维了

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [81]:
a  #原来的数组没有改变

array([[1, 2],
       [3, 4],
       [5, 6]])

In [83]:
np.insert(a,1,[11],axis = 0) # 按行插入

array([[ 1,  2],
       [11, 11],
       [ 3,  4],
       [ 5,  6]])

In [84]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [85]:
np.insert(a,1,[11],axis = 1) #按列插入

array([[ 1, 11,  2],
       [ 3, 11,  4],
       [ 5, 11,  6]])

### 3 reshape()

In [86]:
a = np.arange(12).reshape(3,4)

In [87]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 4 delete()

In [88]:
np.delete(a,6)# 删除指定位置的元素后，变成一维了

array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11])

In [89]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.delete(a,1,axis = 0)

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [91]:
a  # 并不会修改原来的数组

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
np.delete(a,1,axis = 1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

### 5  `unique()`

##### Returns the sorted unique elements of an array.

Returns:
      
       unique_ndarray
       unique_indices_ndarray, optional
       unique_inverse_ndarray, optional
       unique_counts_ndarray, optional


##### （1） unique_ndarray 

In [93]:
a = np.array([0,1,4,7,2,1,4,3])
a

array([0, 1, 4, 7, 2, 1, 4, 3])

In [94]:
np.unique(a)

array([0, 1, 2, 3, 4, 7])

In [95]:
b = np.array([[0,1,4,],[7,2,1],[4,3,0]])
b

array([[0, 1, 4],
       [7, 2, 1],
       [4, 3, 0]])

In [96]:
np.unique(b)

array([0, 1, 2, 3, 4, 7])

In [97]:
np.unique(b,axis=0)

array([[0, 1, 4],
       [4, 3, 0],
       [7, 2, 1]])

In [98]:
np.unique(b,axis=1)

array([[0, 1, 4],
       [7, 2, 1],
       [4, 3, 0]])

In [99]:
b = np.array([[0,1,4,],[7,2,1],[4,3,0],[0,1,4,]])
b

array([[0, 1, 4],
       [7, 2, 1],
       [4, 3, 0],
       [0, 1, 4]])

In [100]:
np.unique(b,axis=0)

array([[0, 1, 4],
       [4, 3, 0],
       [7, 2, 1]])

In [101]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [102]:
a = np.array([[1, 1], [2, 3]])
np.unique(a)

array([1, 2, 3])

##### （2） Return the unique rows of a 2D array

In [104]:
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
a

array([[1, 0, 0],
       [1, 0, 0],
       [2, 3, 4]])

In [103]:
np.unique(a, axis=0)

array([[1, 0, 0],
       [2, 3, 4]])

##### （3） Return the indices of the original array that give the unique values:

In [105]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
u, indices = np.unique(a, return_index=True)
u

array(['a', 'b', 'c'], dtype='<U1')

In [106]:
indices

array([0, 1, 3], dtype=int64)

In [107]:
a[indices]

array(['a', 'b', 'c'], dtype='<U1')

##### （4） Reconstruct the input array from the unique values:

In [108]:
a = np.array([1, 2, 6, 4, 2, 3, 2])
a

array([1, 2, 6, 4, 2, 3, 2])

In [112]:
u, indices = np.unique(a, return_inverse = True)


In [113]:
indices

array([0, 1, 4, 3, 1, 2, 1], dtype=int64)

In [114]:
u

array([1, 2, 3, 4, 6])

In [115]:
u[indices]

array([1, 2, 6, 4, 2, 3, 2])

#### 6 numpy中赋值、视图、深复制

##### （1）赋值

当对numpy数组进行赋值时，只是对同一个对象新建了一个引用，并不是建立新的对象，所以赋值前后的变量完全是同一对象，对其中一个引用修改时，所有引用都会生效：

a = np.arange(12)
b = a # 赋值
a is b

b.shape = (3, 4)
b
a


##### （2）视图（切片、浅复制）

numpy中允许不同数组间共享数据，这种机制在numpy中称为视图，对numpy数组的切片和浅复制都是通过视图实现的。如果数组B是数组A的视图(view)，则称A为B的base(除非A也是视图)。视图数组中的数据实际上保存在base数组中。

In [ ]:
a = np.arange(12)
b = a.view() # 使用视图
a is b

In [ ]:
b

In [ ]:
b.shape = (3, 4) # 改变b的形状
a

In [ ]:
b

In [ ]:
b[0] = 0
a

In [ ]:
b

从上面代码中我们可以发现，a和b是不同的两个数组，改变b的形状对a不会有影响，但是改变b的数据之后，a的数据也会发现改变，说明a与b是共享数据的。

再来探索一些切片：

In [ ]:
a = np.arange(12)
b = a[:] # 切片
a is b

In [ ]:
b.shape = (3, 4)
a

In [ ]:
b

In [ ]:
b[0] = 0
a

In [ ]:
b


果然，切片效果与视图一致。

##### （3）深复制

深复制通过数组自带的copy()方法实现，深复制产生的数组与原数组时完全不同的两个数组对象，完全享有独立的内存空间，所有操作都不会相互影响。

In [ ]:
a = np.arange(12)
b = a.copy()
a is b

b.shape = (3, 4)
b[0] = 0
a

b