> For:《Python语言与应用》<br>
> By：上海大杨晓明<br>
> Created date: 2020.03.27
---

# Chapter_06_01 numpy数组及其运算(2)

## 6.1.4 数组与标量的运算

In [ ]:
import numpy as np
x = np.array((1, 2, 3, 4, 5))    # 创建数组对象
x

In [ ]:
x * 2                            # 数组与数值相乘，返回新数组

In [ ]:
x / 2                            # 数组与数值相除

In [ ]:
x // 2                           # 数组与数值整除

In [ ]:
x ** 3                           # 幂运算

In [ ]:
x + 2                            # 数组与数值相加

In [ ]:
x % 3                            # 余数

In [ ]:
2 ** x                           # 分别计算2**1、2**2、2**3、2**4、2**5

In [ ]:
2 / x

In [ ]:
63 // x

## 6.1.5  数组与数组的运算

In [ ]:
np.array([1, 2, 3, 4]) + np.array([4, 3, 2, 1])
# 等长数组相加，对应元素相加，返回信数组

In [ ]:
np.array([1, 2, 3, 4]) + np.array([4])
# 数组中每个元素加4，数组不等长，广播

In [ ]:
a = np.array((1, 2, 3))
a + a                         # 等长数组之间的加法运算，对应元素相加

In [ ]:
a * a                         # 等长数组之间的乘法运算，对应元素相乘

In [ ]:
a - a                         # 等长数组之间的减法运算，对应元素相减

In [ ]:
a / a                         # 等长数组之间的除法运算，对应元素相除

In [ ]:
a ** a                        # 等长数组之间的幂运算，对应元素乘方

In [ ]:
a = np.array((1, 2, 3))
a

In [ ]:
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
b

In [ ]:
c = a * b                      # 不同维度的数组与数组相乘，广播
c                              # a中的每个元素乘以b中对应列的元素
                               # a中下标0的元素乘以b中列下标0的元素
                               # a中下标1的元素乘以b中列下标1的元素
                               # a中下标2的元素乘以b中列下标2的元素

In [ ]:
a + b                         # a中每个元素加b中的对应列元素

## 6.1.6  数组排序

- `sort()`:
- `argsort()`: 用来返回一个数组，其中的每个元素为原数组中元素的索引，表示应该把原数组中哪个位置上的元素应该放在这个位置。

- `argmax()`,`argmin()`:分别返回数组中最大元素和最小元素的下标。

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)                # 返回排序后元素的原下标
                                 # 原数组中下标1的元素最小
                                 # 下标2的元素次之
                                 # 下标0的元素最大

In [ ]:
x

In [ ]:
x.sort()                     # 原地排序
x

In [ ]:
x = np.array([3, 1, 2])
np.argsort(x)                # 返回排序后元素的原下标
                                 # 原数组中下标1的元素最小
                                 # 下标2的元素次之
                                 # 下标0的元素最大
x[_]                         # 使用数组做下标，获取对应位置的元素

In [ ]:
x

In [ ]:
x = np.array([3, 1, 2, 4])
x.argmax(), x.argmin()       # 最大值和最小值的下标

In [ ]:
np.argsort(x)

## 6.1.7  数组的内积运算

In [ ]:
import numpy as np

x = np.array((1, 2, 3))
y = np.array((4, 5, 6))
print(np.dot(x, y))         # 输出结果都是32
print(x.dot(y))
print(sum(x*y))


## 6.1.8  访问数组中的元素

In [ ]:
import numpy as np
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
b

In [ ]:
b[0]                   # 第0行所有元素
# 当给与的参数少于轴数时，其它的轴被认为是全选，比如这里获得最后一行，
#  等同于b[-0,:] 

In [ ]:
b[0][0]                
# 第0行第0列的元素

In [ ]:
b[0,2]                 
# 第0行第2列的元素，等价于b[0][2]的形式

In [ ]:
b

In [ ]:
b[[0,1]]               
# 第0行和第1行的所有元素，只指定行下标，不指定列下标，表示所有列
# 等价于 b[[0,1],:]

In [ ]:
b[[0,2,1],[2,1,0]]     # 第0行第2列、第2行第1列、第1行第0列的元素
                       # 第一个列表表示行下标，第二个列表表示列下标

In [ ]:
a = np.arange(10)
a

In [ ]:
a[::-1]               # 反向切片

In [ ]:
a[::2]                # 隔一个取一个元素

In [ ]:
a[:5]                 # 前5个元素

In [ ]:
c = np.arange(25)     # 创建数组
c.shape = 5,5         # 修改数组形状
c

In [ ]:
c[0, 2:5]             # 第0行中下标[2,5)之间的元素值

In [ ]:
c[1]                  # 第1行所有元素
                          # 不指定列下标，表示所有列

In [ ]:
c[2:5, 2:5]           # 行下标和列下标都介于[2,5)之间的元素值
# c[[2,3,4],[2,3,4]]

In [ ]:
c[[2,3,4],[2,3,4]]

In [ ]:
c[[1,3], [2,4]]      # 第1行第2列的元素和第3行第4列的元素

In [ ]:
c[[1,3], 2:4]        # 第1行和第3行的第2、3列

In [ ]:
c

In [ ]:
c[:, [2,4]]          # 第2列和第4列所有元素，对行下标进行切片，冒号表示所有行

In [ ]:
c[:, 3]              # 第3列所有元素

In [ ]:
c[[1,3]]             # 第1行和第3行所有元素

In [ ]:
c[[1,3]][:, [2,4]]   # 第1、3行的2、4列元素

In [ ]:
c

对于多维数组，每个轴都有一个索引index，并以逗号分隔，其索引和切片的方式要多多练习，加深理解：

In [ ]:
b=np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
b[2,3]      # 第3行第4列的元素，注意索引从0开始计数
b[2][3]

In [ ]:
b[0:5, 1]        # 第二列中的每一行，注意区间的左闭合右开的特性

In [ ]:
b[ : ,1]                        # 相当于上面的例子

In [ ]:
b[1:3, : ]                      # 每一列的，第二行和第三行的元素

In [ ]:
b[-1]  
#当给与的参数少于轴数时，其它的轴被认为是全选，比如这里获得最后一行，
#  等同于b[-1,:] array([40, 41, 42, 43])

>在上面的最后例子中，省略了列的索引。有时候，它们会被写作这样的格式x[i,...]。三个连续的圆点，代表其它未给出的所有轴的索引。例如假设有数组x，它有5个轴，那么：

    x[1,2,...]相当于x[1,2,:,:,:]
    x[...,3]相当于x[:,:,:,:,3]
    x[4,...,5,:]相当于x[4,:,:,5,:]

参考下面的例子：

In [ ]:
c = np.array( [[[  0,  1,  2],               
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])

In [ ]:
c.shape

c[1,...]                                   # 等同于c[1,:,:] or c[1]

c[...,2]                                   # 等同于c[:,:,2]

In [ ]:
这是偷懒的做法，不建议大家使用，省不了多少事，但带来的理解困难却很多。

对于多维数组的迭代其实就是对它的第一轴进行迭代，从下例子中可以看出，
每个被打印的对象都是原来的一行：

In [ ]:
for row in b:
    print(row)

In [ ]:
如果想对多维数组进行类似Python列表的那样迭代，可以使用数组的flat属性，如下例所示：

In [ ]:
for element in b.flat:
    print(element)

## 6.1.9  数组对函数运算的支持

Numpy为我们提供了一些列常用的数学函数，比如`sin`、`cos`、`exp`等等，这些被称作‘通用函数’（ufunc）。在Numpy中，这些函数都是对数组的每个元素进行计算，并将结果保存在一个新数组中。

In [1]:
import numpy as np  # from numpy import *
B = np.arange(3)
B
np.

array([0, 1, 2])

In [3]:
#dir(np)

In [4]:
np.exp(B)   # 

array([1.        , 2.71828183, 7.3890561 ])

In [5]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [6]:
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [7]:
x = np.array([1.5,1.6,1.7,1.8])
i,j = np.modf(x)
i,j

(array([0.5, 0.6, 0.7, 0.8]), array([1., 1., 1., 1.]))

In [8]:
x = np.array([[1,4],[6,7]])
y = np.array([[2,3],[5,8]])
np.maximum(x,y)   # 二元通用函数

array([[2, 4],
       [6, 8]])

In [9]:
np.minimum(x,y)

array([[1, 3],
       [5, 7]])

## 6.1.10  改变数组形状

- `reshape()` 用来修改数组的形状，返回新数组但不能改变数组中元素的总数量，

- `resize()` 对数组进行原地修改，并且会根据需要进行补0或丢弃部分元素。

可以通过数组的`shape`属性，查看它的形状：

In [13]:
a = np.floor(10*np.random.random((3,4)))
a

array([[7., 6., 8., 2.],
       [3., 9., 2., 2.],
       [3., 9., 3., 8.]])

In [14]:
a.shape

(3, 4)

上面的例子中，先通过numpy的`random`函数生成一个随机3行4列数组，再对每个元素乘10，最后用`floor`函数取整。

有很多数组方法可以变换它的形状，并且不修改原始数组本身：

In [15]:
a.ravel()  # 平铺数组成为一维数组

array([7., 6., 8., 2., 3., 9., 2., 2., 3., 9., 3., 8.])

In [16]:
a.reshape(6,2)  # 调整形状


array([[7., 6.],
       [8., 2.],
       [3., 9.],
       [2., 2.],
       [3., 9.],
       [3., 8.]])

### 3 转置数组

In [17]:
a.T  # 返回行变成列，列变化行。

array([[7., 3., 3.],
       [6., 9., 9.],
       [8., 2., 3.],
       [2., 2., 8.]])

In [18]:
a

array([[7., 6., 8., 2.],
       [3., 9., 2., 2.],
       [3., 9., 3., 8.]])

In [19]:
a.T.shape

(4, 3)

In [20]:
a.shape

(3, 4)

### 4 `reshape()`方法不会修改数组本身，`resize()`则正好相反：

In [21]:
a

array([[7., 6., 8., 2.],
       [3., 9., 2., 2.],
       [3., 9., 3., 8.]])

In [22]:
a.resize((2,6))
a

array([[7., 6., 8., 2., 3., 9.],
       [2., 2., 3., 9., 3., 8.]])

In [23]:
a.resize((2,7)) # 突发奇想，作死试试

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [24]:
np.resize(a, (2,7)) # 但是...居然可以这么干!    产生新的数组，不改变a

array([[7., 6., 8., 2., 3., 9., 2.],
       [2., 3., 9., 3., 8., 7., 6.]])

In [25]:
a

array([[7., 6., 8., 2., 3., 9.],
       [2., 2., 3., 9., 3., 8.]])

> 再次提醒，在numpy中有各种类似的坑，你根本踩不过来，所以不要尝试一些自己不确定的东西。

- 如果`reshape`方法的一个参数是-1，那么这个参数的实际值会自动计算得出：

In [26]:
a.reshape(3,-1)


array([[7., 6., 8., 2.],
       [3., 9., 2., 2.],
       [3., 9., 3., 8.]])

> 更多内容参考：ndarray.shape, reshape, resize, ravel

## 6.1.11  数组布尔运算


使用布尔数组进行索引，其实就是我们显式地选择数组中需要哪些项，不需要哪些项。

### 1 使用与原始数组形状相同的布尔数组进行筛选过滤：

In [32]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
b = a > 4
b   # 通过比较运算，b变成了一个由布尔值组成的数组

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
a[a>4]        # 生成一个由True值对应出来的一维数组

array([ 5,  6,  7,  8,  9, 10, 11])

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

这个技巧用在特殊位置赋值操作特别高效：

In [31]:
a[b] = 0    #所有a中大于4的元素被重新赋值为0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
a[(a>4) & (a<8)]

array([5, 6, 7])

实际上，上面的操作可以简写成：a[a>4] = 0

> 使用~可以对布尔值取反，|表示或，&表示与：

In [37]:
a[~b]

array([0, 1, 2, 3, 4])

In [36]:
(a<4)|(a>7)

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [38]:
a[(a>3)&(a<8)]

array([4, 5, 6, 7])

In [39]:
(a>3)&(a<8)

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False, False]])

### 2 使用布尔数组索引的方法:

In [40]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b1 = np.array([False,True,True]) 

In [42]:
b2 = np.array([True,False,True,False]) 

In [43]:
a[b1,:]                                 

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a[b1]                                   

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[:,b2]                                  

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [46]:
a[b1,b2]   
# b1         Falase  True     True            -> [1,2]          
# b2         True    False   True    False    -> [0,2]
# a[[1,0],[2,2]]

array([ 4, 10])

In [47]:
a[[1,2],[0,2]]

array([ 4, 10])

In [48]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 6.1.12  分段函数

numpy提供了`where()`和`piecewise()`两个函数支持分段函数对数组的处理，

### 1 `where()`

适合对原数组进行“二值化”，根据数组中的元素是否满足指定的条件返回x还是y。语法如下：
      
      where(condition,[x,y])
      

In [53]:
import numpy as np
x = np.random.randint(0, 10, size=(1,10))
x

array([[0, 7, 9, 5, 8, 1, 2, 6, 0, 4]])

In [50]:
np.where(x<5, 0, 1)          # 小于5的元素值对应0，其他对应1

array([[0, 0, 0, 0, 0, 1, 0, 1, 0, 0]])

### 2 `piecewise()`

可以实现更复杂的处理，语法如下：

      piecewise(x,condlist,funclist,*args,**kw)

In [54]:
x

array([[0, 7, 9, 5, 8, 1, 2, 6, 0, 4]])

In [55]:
np.piecewise(x, [x<4, x>7], [lambda x:x*2, lambda x:x*3])
 # 小于4的元素乘以2，大于7的元素乘以3，其他元素变为0

array([[ 0,  0, 27,  0, 24,  2,  4,  0,  0,  0]])

In [56]:
np.piecewise(x, [x<3, (3<x)&(x<5), x>7], [-1, 1, lambda x:x*4])
# 小于3的元素变为-1，大于3小于5的元素变为1，大于7的元素乘以4
# 条件没有覆盖到的其他元素变为0

array([[-1,  0, 36,  0, 32, -1, -1,  0, -1,  1]])

## 6.1.13 数组堆叠与合并

### 1`hstack()`和`vstack()`函数

In [57]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
np.hstack((arr1,arr2))        # 水平堆叠

array([1, 2, 3, 4, 5, 6])

In [58]:
np.vstack((arr1,arr2))        # 垂直堆叠

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr3 = np.array([[1],[2],[3]])
arr3

array([[1],
       [2],
       [3]])

In [59]:
arr4 = np.array([[4],[5],[6]])

In [61]:
np.hstack((arr3,arr4))        # 水平堆叠

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
np.vstack((arr3,arr4))        # 垂直堆叠

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

###  2 `concatenate()`函数

提供了类似的数据合并功能，其参数`axis`用来指定沿哪个方向或维度进行合并，默认为0，也就是按行进行合并。

In [63]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [64]:
np.concatenate((arr3,arr4))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [65]:
np.concatenate((arr3,arr4),axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])